name: yanapay
description: "Marketplace web3"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-134.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  web3dart: ^2.7.2
  web_socket_channel: ^2.4.0

  cupertino_icons: ^1.0.2

  octo_image: ^2.0.0
  dots_indicator: ^2.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  bottom_sheet: ^3.1.2
  cached_network_image: 3.3.0
  flutter_feather_icons: ^2.0.0+1
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.2
  flutter_swiper_null_safety: ^1.0.2
  fluttertoast: ^8.2.1
  form_field_validator: ^1.1.0
  get: ^4.6.5
  google_fonts: ^4.0.3
  intl: ^0.18.1
  modal_bottom_sheet: ^2.1.2
  provider: ^6.0.5
  pull_to_refresh: ^2.0.0
  readmore: ^2.2.0
  responsive_grid: ^2.1.0
  smooth_star_rating:
    git:
      url: https://github.com/educup/smoothratingbar
  timeline_tile: ^2.0.0
  very_good_analysis: ^4.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

